spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exodia_inventario_test
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ah18059}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false

logging:
  level:
    com.exodia.inventario: DEBUG
